### ISSUE TITLE
byzer启动失败

### ISSUE THREAD

**Issue by winbina** [byzer-org/byzer-k8s#2]
安装官方文档，执行后k8s命令后，出现如下几个问题：
1、ingress部署失败，提示 【Fail to create ingress for mlsql-engine: unable to recognize "./2124599810": no matches for kind "Ingress" in version "networking.k8s.io/v1"】
2、pod无法启动执行，执行log出现如下提示：
[root@win-master1 byzer-k8s-master]# kubectl logs  mlsql-engine-f966f9754-g8mjj
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/work/spark-3.1.1-bin-hadoop3.2/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
22/01/05 03:10:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/01/05 03:10:01 WARN DependencyUtils: Local jar /home/deploy/mlsql/libs/streamingpro-mlsql-spark_3.0_2.12-2.1.0.jar does not exist, skipping.
Error: Failed to load class streaming.core.StreamingApp.
22/01/05 03:10:01 INFO ShutdownHookManager: Shutdown hook called
22/01/05 03:10:01 INFO ShutdownHookManager: Deleting directory /tmp/spark-07bc5351-954f-4103-9763-f2661e9d6037

**Comment by winbina** [comment]
官方文档的版本是-2.1.0-SNAPSHOP.jar
Dockerfile里面的版本是-2.2.0-SNAPSHOP.jar，应该修改你们的官方文档
local:///home/deploy/mlsql/libs/streamingpro-mlsql-spark_3.0_2.12-2.2.0-SNAPSHOT.jar

**Comment by allwefantasy** [comment]
Can anyone fix this？ @MichelZhan @hellozepp
